resources:
  - name: my_source
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: elioengcomp/project-examples
      branches:
        include: master

  - name: base_image
    type: Image
    configuration:
      registry: my_art
      sourceRepository: default-docker
      imageName: elioengcomp.jfrog.io/default-docker/node
      imageTag: latest
      autoPull: true

  - name: hello_world_image
    type: Image
    configuration:
      registry: my_art
      sourceRepository: default-docker
      imageName: elioengcomp.jfrog.io/default-docker/helloworld
      imageTag: latest
      autoPull: true

  - name: image_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: my_art
      buildName: hello_world_build
      buildNumber: 1

pipelines:
  - name: build_hello_world
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: default-npm
          sourceLocation: ./npm-example
          inputResources:
            - name: my_source
          integrations:
            - name: my_art

      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: docker_group
          dockerFileLocation: ./npm-example
          dockerFileName: Dockerfile
          dockerImageName: elioengcomp.jfrog.io/default-docker/helloworld    # replace with your fully qualified Docker registry/image name
          dockerImageTag: ${run_number}
          inputSteps:
            - name: build_npm
          inputResources:
            - name: my_source
            - name: base_image
          integrations:
            - name: my_art

      - name: push_image
        type: DockerPush
        configuration:
          affinityGroup: docker_group
          targetRepository: default-docker
          integrations:
            - name: my_art
          inputSteps:
            - name: build_image
          outputResources:
            - name: hello_world_image

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: push_image
          outputResources:
            - name: image_build_info
